name: documentation
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
          submodules: true # fetchmkdocs-material
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          update-environment: false
      - run: pip install -r requirements.txt # mkdocs-material mkdocs-redirects mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
